dist: xenial
sudo: false

language: python

python:
  # - "3.5"
  # - "3.6"
  - "3.7"
  # - "3.8-dev"

matrix:
  fast_finish: true
  # allow_failures:
  #   - python: "3.6"
  #   - python: "3.7"
  #   - python: "3.8-dev"

install:
  - "pip install coveralls tox tox-travis"

script:
  - "tox"

after_success:
  - "coveralls"
